userNames:
users:
  affix:
    prefix:
    suffix:
usercaches:
  affix:
    prefix:
    suffix:
commandNames:
  - cuteplayerchat
  - getsuf
  - getsufall
  - setsuf
  - setsufall
  - delsuf
  - delsufall
  - getpre
  - getpreall
  - setpre
  - setpreall
  - delpre
  - delpreall
commands:
  cuteplayerchat: [ cuteplayerchat, cpc ]

  getsuf: [ getsuf, gs ]
  getsufall: [ getsufall, gsa ]
  setsuf: [ setsuf, ss ]
  setsufall: [ setsufall, ssa ]
  delsuf: [ delsuf, ds ]
  delsufall: [ delsufall, dsa ]

  getpre: [ getpre, gp ]
  getpreall: [ getpreall, gpa ]
  setpre: [ setpre, sp ]
  setpreall: [ setpreall, spa ]
  delpre: [ delpre, dp ]
  delpreall: [ delpreall, dpa ]

default-config:
  affix:
    prefix: '嗷呜'
    suffix: '喵'