name: CutePlayerChat
version: 'v0.2.1'
main: com.eofitg.cuteplayerchat.CutePlayerChat
api-version: 1.18
authors: [ eofitg ]
description: Make players‘ chat more cute!

commands:
  cuteplayerchat:
    description: CPC plugin's setup and management.
    usage: /cuteplayerchat help
    permission: cuteplayerchat.help
    permission-message: §4权限不足，无法执行！
  getsuff:
    description: Get the players' suffixes
    usage: /getsuff [playerName_1] ... [playerName_n]
    permission: cuteplayerchat.getsuff
    permission-message: §4权限不足，无法查看！
  getsuffall:
    description: Get all the players' suffixes
    usage: /getsuffall
    permission: cuteplayerchat.getsuffall
    permission-message: §4权限不足，无法查看！
  setsuff:
    description: Set the suffix
    usage: /setsuff [playerName_1] ... [playerName_n] <suffix>
  setsuffall:
    description: Set all the suffix
    usage: /setsuffall <suffix>
  delsuff:
    description: Delete the suffix
    usage: /delsuff [playerName_1] ... [playerName_n]
    permission: cuteplayerchat.delsuff
    permission-message: §4权限不足，无法删除!
  delsuffall:
    description: Delete all the suffix
    usage: /delsuffall
    permission: cuteplayerchat.delsuffall
    permission-message: §4权限不足，无法删除!